# Use an official Node.js image as the base image
FROM node:latest as build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN yarn install

# Copy the rest of the project files to the working directory
COPY . .
# Define the default command to run the development server
RUN npm run build

FROM nginx:1.17.0-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Validate Nginx Command
RUN nginx -t