export const GET_TRIPS = "GET_TRIPS";
export const SEARCH_TRIP = "SEARCH_TRIP";
export const SEARCH_TRIP_SUCCESS = "SEARCH_TRIP_SUCCESS";

export const GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";
export const CLEAR_SEARCH_STATE = "CLEAR_SEARCH_STATE";

export const SET_REQUEST_STATUS = "SET_REQUEST_STATUS";
export const SET_AUTH_STATUS = "SET_AUTH_STATUS";
export const IS_AUTHENTICATING = "IS_AUTHENTICATING";
export const LOADING = "LOADING";
