export const STAFF_SIGNIN = 'STAFF_SIGNIN';
export const STAFF_SIGNIN_SUCCESS = 'STAFF_SIGNIN_SUCCESS';
export const STAFF_SIGNUP = 'STAFF_SIGNUP';
export const STAFF_SIGNUP_SUCCESS = 'STAFF_SIGNUP_SUCCESS';
export const STAFF_SIGNOUT = 'STAFF_SIGNOUT';
export const STAFF_SIGNOUT_SUCCESS = 'STAFF_SIGNOUT_SUCCESS';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const ON_STAFF_AUTHSTATE_SUCCESS = 'ON_STAFF_AUTHSTATE_SUCCESS';
export const ON_STAFF_AUTHSTATE_FAIL = 'ON_STAFF_AUTHSTATE_FAIL';
export const STAFF_RESET_PASSWORD = 'RESET_PASSWORD';

export const ON_AUTHSTATE_CHANGED = 'ON_AUTHSTATE_CHANGED';
export const SET_AUTH_PERSISTENCE = 'SET_AUTH_PERSISTENCE';

export const LOADING = 'LOADING';
export const IS_AUTHENTICATING = 'IS_AUTHENTICATING';
export const SET_REQUEST_STATUS = 'SET_REQUEST_STATUS';